FBStudentFeedback/src/main/java/com/fbsearch/managedbean/FacebookCrawlingBean.java
package com.fbsearch.managedbean;

import com.fbsearch.domains.Comments;
import com.fbsearch.domains.Data;
import com.fbsearch.domains.FBComment;
import com.fbsearch.domains.FBFirstLevel;
import com.fbsearch.domains.FBGroup;
import com.fbsearch.domains.FBPost;
import com.fbsearch.domains.FBSecondLevel;
import com.fbsearch.domains.Feed;
import com.fbsearch.domains.Likes;
import com.fbsearch.utils.GSonBinding;
import com.fbsearch.utils.ReadFromAnExcelFile;
import com.fbsearch.utils.ThaiWordbreak;
import com.google.common.collect.Lists;
import com.ibm.icu.text.BreakIterator;
import com.stc.CompactTree;
import com.stc.STCClustering;
import com.stc.SuffixTree;
import com.stc.stemmer;
import com.stc.stopword;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.io.Reader;
import java.io.Serializable;
import java.io.StringReader;
import java.net.URL;
import java.nio.charset.Charset;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.Locale;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import org.primefaces.json.JSONException;
import org.primefaces.json.JSONObject;
import org.primefaces.model.chart.PieChartModel;

@ManagedBean
public class FacebookCrawlingBean implements Serializable {
    /*Replace your confix here*/
    private static final int recursiveLoop = 10; //maximun cawling is 100 activities.
    private static final String EXCEL_PATH = "/Users/Pu/NetBeansProjects/fbstudentfeedback/";
    /*Ended*/
    private String accessToken;
    private String groupId;
    private Date startDate = new Date();
    private Date endDate = new Date();
    private PieChartModel pieModel1;
    private String resultDetail;
    private static final String DESTINATION_NM = "https://graph.facebook.com/v2.4/";
    private static final String GET_POST_ID_LIST_CMD = "%s?fields=id,name,description,feed.since(%s).until(%s){id}";
    private static final String GET_POST_COMMENT_LIST_CMD = "%s?fields=message,comments{message},likes.summary(true)";
    private static final String GET_GROUP_MEMBER_CMD = "%s?499083853497753/members?limit=200";
    private FBGroup fbGroup = new FBGroup("-", "-");
    private List<String> symbolList = Lists.newArrayList();
    private List<String> positiveList = Lists.newArrayList();
    private List<String> negativeList = Lists.newArrayList();
    private List<String> inactionList = Lists.newArrayList();
    private PrintStream out;
    private int totalPost;
    private int goodFeedback;
    private int badFeedback;
    private int normalfeedback;
    private String requestUrl;
    private int totalSnippet;
    private StringBuilder stcOutputbuilder;

    public void clearAll() {
        accessToken = null;
        groupId = null;
        startDate = new Date();
        endDate = new Date();
        createPieModel(0, 0, 0);
        resultDetail = "";
        fbGroup = new FBGroup("-", "-");
        totalPost = 0;
        goodFeedback = 0;
        badFeedback = 0;
        normalfeedback = 0;
        requestUrl = "";
        totalSnippet = 0;
        stcOutputbuilder = null;
    }

    @PostConstruct
    public void init() {
        createPieModel(0, 0, 0);
        try {
            generateListFromExcelFile();
            this.out = new PrintStream(System.out, true, "TIS-620");
        } catch (Exception ex) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, ex.getMessage(), null));
            Logger.getLogger(FacebookCrawlingBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void generateListFromExcelFile() throws IOException {
        ReadFromAnExcelFile readExcel = new ReadFromAnExcelFile();
        symbolList = readExcel.readDataFromExcelFile(EXCEL_PATH, "symbol.xlsx", "symbol");
        positiveList = readExcel.readDataFromExcelFile(EXCEL_PATH, "keywords.xlsx", "positive");
        negativeList = readExcel.readDataFromExcelFile(EXCEL_PATH, "keywords.xlsx", "negative");
        inactionList = readExcel.readDataFromExcelFile(EXCEL_PATH, "keywords.xlsx", "inaction");
    }

    public void crawlingData() {
        totalPost = 0;
        requestUrl = "";
        try {
            SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd,hh:mm:ss");
            fmt.setCalendar(GregorianCalendar.getInstance());
            StringBuilder fbRquestUrl = new StringBuilder();
            fbRquestUrl.append(DESTINATION_NM);
            fbRquestUrl.append(groupId);
            fbRquestUrl.append("?fields=id,name,description,feed.since(");
            fbRquestUrl.append(fmt.format(startDate));
            fbRquestUrl.append(").until(");
            fbRquestUrl.append(fmt.format(endDate));
            fbRquestUrl.append("){id}&access_token=");
            fbRquestUrl.append(accessToken);
            out.print(fbRquestUrl);
            requestUrl = fbRquestUrl.toString();
            clientServiceGet(requestUrl);

            doTextCleaning();
            doClustering();
            doSTCClustering();

        } catch (IOException | JSONException ex) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, ex.getMessage(), null));
            Logger.getLogger(FacebookCrawlingBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clientServiceGet(String requestUrl) throws IOException, JSONException {

        JSONObject json = readJsonFromUrl(requestUrl);
        out.println(json.toString());
        resultDetail = json.toString();
        System.out.println("query1: " + resultDetail);
        FBFirstLevel firstLevel = GSonBinding.convertToFirstLevelObject(resultDetail);
        FBGroup group = this.fbGroup;
        group.setGroupId(firstLevel.getId());
        group.setGroupName(firstLevel.getName());
        group.setGroupDesc(firstLevel.getDescription());
        Feed firstLevelFeed = firstLevel.getFeed();
        System.out.println("Number of first page feed :" + firstLevelFeed.getData().size());
        totalPost = firstLevelFeed.getData().size();

        for (int i = 1; i <= recursiveLoop; i++) {
            firstLevelFeed = recursiveFeedData(i, firstLevelFeed);
        }

        List<FBPost> postList = Lists.newArrayList();
        for (Data data : firstLevelFeed.getData()) {
            String id = data.getId();
            String updateTime = data.getUpdated_time();
            String secRequestUrl = DESTINATION_NM + id + "?fields=message,comments{message},likes.summary(true)&access_token=" + accessToken;
            json = readJsonFromUrl(secRequestUrl);
            out.println(json.toString());
            resultDetail = json.toString();
            FBSecondLevel secondLevel = GSonBinding.convertToSecondLevelObject(resultDetail);

            FBPost post = new FBPost();
            post.setPostMessage(secondLevel.getMessage());
            if (updateTime != null) {
                post.setUpdateTime(updateTime);
            }
            Likes like = secondLevel.getLikes();
            post.setTotalLike(like.getSummary().getTotal_count());
            Comments comment = secondLevel.getComments();
            if (comment != null) {
                List<Data> commentData = comment.getData();
                List<FBComment> fBCommentList = Lists.newArrayList();
                for (Data cData : commentData) {
                    FBComment fbComment = new FBComment();
                    fbComment.setCommentId(cData.getId());
                    fbComment.setCommentDetail(cData.getMessage());
                    fBCommentList.add(fbComment);
                }
                post.setCommentList(fBCommentList);
            }
            postList.add(post);
            group.setPostList(postList);
        }
        this.fbGroup = group;
    }

    private Feed recursiveFeedData(int count, Feed feed) throws IOException, JSONException {
        if (feed.getPaging() != null && feed.getPaging().getNext() != null) {
            String nextPageUrl = feed.getPaging().getNext();
            JSONObject json = readJsonFromUrl(nextPageUrl);
            Feed pagingData = GSonBinding.convertToNextPageLevelObject(json.toString());
            List<Data> pagingDataList = pagingData.getData();
            feed.getData().addAll(pagingDataList);
            System.out.println("Number of " + count + " page feed :" + feed.getData().size());
            totalPost = feed.getData().size();
        }
        return feed;
    }

    private void doTextCleaning() {
        for (FBPost post : this.fbGroup.getPostList()) {
            if (post.getPostMessage() != null) {
                String postAfterClean = textCleaning(post.getPostMessage());
                String postAfterBreak = doThaiWordBreak(postAfterClean);
                post.setPostMessage(postAfterBreak);
            }
            for (FBComment comment : post.getCommentList()) {
                if (comment.getCommentDetail() != null) {
                    String textAfterClean = textCleaning(comment.getCommentDetail());
                    String textAfterBreak = doThaiWordBreak(textAfterClean);
                    comment.setCommentDetail(textAfterBreak);
                }
            }
        }
    }

    public int getTotalLike() {
        int total = 0;
        for (FBPost post : this.getFbGroup().getPostList()) {
            total = total + post.getTotalLike();
        }
        return total;
    }

    private String doThaiWordBreak(String text) {
        String s = "wrong input!";
        Locale thaiLocale = new Locale("th");

FBStudentFeedback/src/main/webapp/pages/howitworks.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<ui:composition template="/template/responsiveLayout.xhtml"  
                xmlns="http://www.w3.org/1999/xhtml" 
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:ui="http://java.sun.com/jsf/facelets">   
    <ui:define name="centerReplace" >
        <h:body>
            <h:form id="mainForm"> 
                <p:messages id="message2" showDetail="true" autoUpdate="true" closable="true" />
                <p:panel  header="How it works" toggleable="true" >
                    <h:panelGrid id="mainPng" style="text-align: left !important;">
                        <h:outputText value="1. Login facebook." />
                        <h:outputText value="2. Go to facebook group that you want to retrive data."/>
                        <h:outputText value="3. Copy group id from URL e.g.499083853497753."/>
                        <h:outputText value="4. Go to GraphAPIExplorer tool belows."/>
                        <h:outputLink id="requestLink" value="https://developers.facebook.com/tools/explorer/" target="_blank">
                            <h:outputText value="https://developers.facebook.com/tools/explorer/" style="font-size: smaller"/>
                        </h:outputLink>
                        <h:outputText value="5. Register the app and set authentication."/>
                        <h:outputText value="6. Copy access token and paste to this app."/>
                    </h:panelGrid>
                </p:panel>
            </h:form>   
        </h:body>
    </ui:define>
</ui:composition>

FBStudentFeedback/src/main/webapp/pages/index.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<ui:composition template="/template/responsiveLayout.xhtml"  
                xmlns="http://www.w3.org/1999/xhtml" 
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:fn="http://java.sun.com/jsp/jstl/functions">   
    <ui:define name="centerReplace" >
        <style>
            .panelGrid tr, .panelGrid td{
                border:none !important;
            }

            .ui-panelgrid-cell{
                text-align: left !important;
            }
        </style>
        <h:body>
            <script type="text/javascript">
                function exportChart() {
                    //export image
                    $('#output').empty().append(PF('chart').exportAsImage());
                    //show the dialog
                    PF('dlg').show();
                }
            </script>
            <h:form id="mainForm"> 
                <p:messages id="message2" showDetail="true" autoUpdate="true" closable="true" />
                <p:panel header="Facebook Input Criteria" toggleable="true" >
                    <p:panelGrid styleClass="panelGrid" columns="2">
                        <h:outputLabel value="Group ID:"/>
                        <h:inputText value="#{facebookCrawlingBean.groupId}" size="60" style="width:100%;" required="true" requiredMessage="Group ID is required"/>
                        <h:outputLabel value="Access Token:"/>
                        <h:inputText value="#{facebookCrawlingBean.accessToken}"  size="60" style="width:100%;" required="true" requiredMessage="Access Token is required"/>
                        <h:outputLabel value="since:"/>
                        <p:calendar id="button1" value="#{facebookCrawlingBean.startDate}" showOn="button" size="12" 
                                    pattern="dd/MM/yyyy" required="true" requiredMessage="Since is required" />
                        <h:outputLabel value="until:"/>
                        <p:calendar id="button2" value="#{facebookCrawlingBean.endDate}" showOn="button" size="12"
                                    pattern="dd/MM/yyyy" required="true" requiredMessage="Until is required" />
                    </p:panelGrid>
                    <p:spacer/>
                    <h:panelGrid columns="2">
                        <p:commandButton  value="Generate" icon="ui-icon-refresh" update="requestLink, result, :output" actionListener="#{facebookCrawlingBean.crawlingData}"/>
                        <p:commandButton  value="Clear" icon="ui-icon-refresh" update="mainForm" actionListener="#{facebookCrawlingBean.clearAll}"/>
                    </h:panelGrid>
                    <h:outputLink id="requestLink" value="#{facebookCrawlingBean.requestUrl}" target="_blank">
                        <h:outputText value="#{facebookCrawlingBean.requestUrl}" style="font-size: smaller"/>
                    </h:outputLink>
                </p:panel>
                <p:panel id="result" header="Chart Result" toggleable="true">
                    <p:chart id="pieResult" type="pie" model="#{facebookCrawlingBean.pieModel1}"  widgetVar="chart"/>
                    <p:commandButton type="button" value="Export" icon="ui-icon-extlink" onclick="exportChart();"/>
                    <h:outputLabel value="#{facebookCrawlingBean.fbGroup.groupName}" style="width:100%;"/>
                    <h:outputLabel value="#{facebookCrawlingBean.fbGroup.groupDesc}" style="width:100%;"/>
                    <p:panel id="toggleable" header="Facebook Crawling Result" toggleable="true" toggleSpeed="500" closeSpeed="500" widgetVar="panel" >
                        <p:dataTable value="#{facebookCrawlingBean.fbGroup.postList}" var="fbpost" >
                            <p:subTable var="fbcomment" value="#{fbpost.commentList}">
                                <f:facet name="header">
                                    <p:outputPanel style="float: left">        
                                        <h:outputText value="#{fbpost.postMessage}: #{fbpost.updateTime}"/>
                                    </p:outputPanel>
                                </f:facet>
                                <p:column headerText="Comment" style="text-align: left;">
                                    <h:outputText value="#{fbcomment.commentDetail}" />
                                </p:column>
                            </p:subTable>
                        </p:dataTable>
                        <h:outputText value="total Likes : #{facebookCrawlingBean.totalLike}, total post : #{facebookCrawlingBean.totalPost}, total snippets : #{facebookCrawlingBean.totalSnippet}"  />
                    </p:panel>
                    <p:panel id="toggleable2" header="STC Result" toggleable="true" toggleSpeed="500" closeSpeed="500" widgetVar="panel2" >
                        <h:outputText value="#{facebookCrawlingBean.stcResult}" escape="false"/>
                    </p:panel>
                </p:panel>
            </h:form>   
            <p:dialog widgetVar="dlg" showEffect="fade" modal="true" header="Chart as an Image" resizable="false">
                <p:outputPanel id="output" layout="block" />
            </p:dialog>
        </h:body>
    </ui:define>
</ui:composition>